version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔹 Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 208116833517.dkr.ecr.ap-south-1.amazonaws.com
      - echo "🔹 Getting commit hash..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - REPOSITORY_URI=208116833517.dkr.ecr.ap-south-1.amazonaws.com/sample-server

  build:
    commands:
      - echo "🔹 Build started on $(date)"
      - echo "🔹 Building Docker image..."
      - cd services/user-service                # ✅ Go inside service
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "🔹 Build completed on $(date)"
      - echo "🔹 Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
